apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  user: cm9vdA==
  password: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  user: YWRtaW4=
  password: aXQ5SmF1WGxvTw==
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  password: cVQ2dERQZ3BnbA==